#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ImageGallery.Resource", IsApplication=true)]

namespace ImageGallery
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080007
			public const int action_image_from_camera = 2131230727;
			
			// aapt resource value: 0x7f080006
			public const int action_image_from_gallery = 2131230726;
			
			// aapt resource value: 0x7f080002
			public const int etext_comment = 2131230722;
			
			// aapt resource value: 0x7f080004
			public const int img_image = 2131230724;
			
			// aapt resource value: 0x7f080000
			public const int layout_fragment_container = 2131230720;
			
			// aapt resource value: 0x7f080003
			public const int layout_img_with_loc = 2131230723;
			
			// aapt resource value: 0x7f080001
			public const int list_comments = 2131230721;
			
			// aapt resource value: 0x7f080005
			public const int text_location = 2131230725;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f040000
			public const int grid_view_column_count = 2130968576;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ActivityMain = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DetailedImageView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FileUriLoadImageView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ImageWithLocations = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int OverviewImageGallery = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int Main = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int action_import_from_camera = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int action_import_from_gallery = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int dialog_title_remove = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int images_directory_name = 2131034116;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Mono_Android_Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
